"""Executable Serve profiles for the external TTFT campaigns."""

from __future__ import annotations


def _args(*values: str | int) -> tuple[str, ...]:
    return tuple(str(value) for value in values)


COMMON_ARGS = _args(
    "--kv-dtype",
    "fp8",
    "--no-thinking",
    "--greedy",
    "--log-stats-interval-ms",
    0,
)


PROFILE_ARGS: dict[str, tuple[str, ...]] = {
    "text-cold-8k": _args(
        "--max-context", 8192,
        "--kv-capacity", 8192,
        "--max-concurrency", 1,
        "--no-prefix-reuse",
    ),
    "text-cold-64k": _args(
        "--max-context", 65536,
        "--kv-capacity", 65536,
        "--max-concurrency", 1,
        "--no-prefix-reuse",
    ),
    "text-cold-256k": _args(
        "--max-context", 262144,
        "--kv-capacity", 262144,
        "--max-concurrency", 1,
        "--no-prefix-reuse",
    ),
    "cache-hot": _args(
        "--max-context", 8192,
        "--kv-capacity", 8192,
        "--max-concurrency", 1,
        "--device-state-slots", 2,
        "--host-state-slots", 0,
        "--host-kv-mib", 0,
        "--max-private-continuations", 2,
        "--max-shared-prefixes", 0,
        "--max-long-anchors-per-continuation", 0,
    ),
    "cache-state-working-set": _args(
        "--max-context", 32768,
        "--kv-capacity", 32768,
        "--max-concurrency", 1,
        "--prefill-chunk", 1024,
        "--spec", "dflash2",
        "--draft-tokens", 7,
        "--lm-head-draft",
        "--device-state-slots", 8,
        "--host-state-slots", 8,
        "--host-kv-mib", 0,
        "--max-private-continuations", 8,
        "--max-shared-prefixes", 8,
        "--max-long-anchors-per-continuation", 0,
    ),
    "cache-private-working-set": _args(
        "--max-context", 32768,
        "--kv-capacity", 32768,
        "--max-concurrency", 1,
        "--prefill-chunk", 1024,
        "--spec", "dflash2",
        "--draft-tokens", 7,
        "--lm-head-draft",
        "--device-state-slots", 2,
        "--host-state-slots", 2,
        "--host-kv-mib", 0,
        "--max-private-continuations", 8,
        "--max-shared-prefixes", 0,
        "--max-long-anchors-per-continuation", 0,
    ),
    "cache-pressure-device": _args(
        "--max-context", 8192,
        "--kv-capacity", 16384,
        "--max-concurrency", 2,
        "--device-state-slots", 2,
        "--host-state-slots", 0,
        "--host-kv-mib", 0,
        "--max-private-continuations", 4,
        "--max-shared-prefixes", 0,
        "--max-long-anchors-per-continuation", 0,
    ),
    "cache-pressure-state-host": _args(
        "--max-context", 8192,
        "--kv-capacity", 16384,
        "--max-concurrency", 2,
        "--device-state-slots", 0,
        "--host-state-slots", 4,
        "--host-kv-mib", 0,
        "--max-private-continuations", 4,
        "--max-shared-prefixes", 0,
        "--max-long-anchors-per-continuation", 0,
    ),
    "cache-pressure-kv-host": _args(
        "--max-context", 8192,
        "--kv-capacity", 8192,
        "--max-concurrency", 2,
        "--device-state-slots", 2,
        "--host-state-slots", 0,
        "--host-kv-mib", 8192,
        "--max-private-continuations", 4,
        "--max-shared-prefixes", 0,
        "--max-long-anchors-per-continuation", 0,
    ),
    "cache-swap-64k-host": _args(
        "--max-context", 65536,
        "--kv-capacity", 65536,
        "--max-concurrency", 2,
        "--device-state-slots", 4,
        "--host-state-slots", 0,
        "--host-kv-mib", 4608,
        "--max-private-continuations", 4,
        "--max-shared-prefixes", 0,
        "--max-long-anchors-per-continuation", 0,
    ),
    "cache-rotation-55k-host": _args(
        "--max-context", 240000,
        "--kv-capacity", 240000,
        "--max-concurrency", 4,
        "--max-pending-requests", 32,
        "--pending-timeout-ms", 120000,
        "--spec", "mtp",
        "--draft-tokens", 3,
        "--lm-head-draft",
        "--device-state-slots", 2,
        "--host-state-slots", 24,
        "--host-kv-mib", 49152,
        "--max-private-continuations", 24,
        "--max-shared-prefixes", 24,
        "--max-long-anchors-per-continuation", 0,
    ),
    "cache-pressure-both-host": _args(
        "--max-context", 8192,
        "--kv-capacity", 8192,
        "--max-concurrency", 2,
        "--device-state-slots", 0,
        "--host-state-slots", 4,
        "--host-kv-mib", 8192,
        "--max-private-continuations", 4,
        "--max-shared-prefixes", 0,
        "--max-long-anchors-per-continuation", 0,
    ),
    "cache-pressure-evict": _args(
        "--max-context", 8192,
        "--kv-capacity", 8192,
        "--max-concurrency", 2,
        "--device-state-slots", 1,
        "--host-state-slots", 0,
        "--host-kv-mib", 0,
        "--max-private-continuations", 4,
        "--max-shared-prefixes", 0,
        "--max-long-anchors-per-continuation", 0,
    ),
    "cache-pressure-catalog": _args(
        "--max-context", 8192,
        "--kv-capacity", 16384,
        "--max-concurrency", 2,
        "--device-state-slots", 2,
        "--host-state-slots", 0,
        "--host-kv-mib", 0,
        "--max-private-continuations", 2,
        "--max-shared-prefixes", 0,
        "--max-long-anchors-per-continuation", 0,
    ),
    "cache-off": _args(
        "--max-context", 8192,
        "--kv-capacity", 8192,
        "--max-concurrency", 1,
        "--no-prefix-reuse",
    ),
    "shared-prefix": _args(
        "--max-context", 8192,
        "--kv-capacity", 16384,
        "--max-concurrency", 2,
        "--device-state-slots", 2,
        "--host-state-slots", 0,
        "--host-kv-mib", 0,
        "--max-private-continuations", 2,
        "--max-shared-prefixes", 1,
        "--max-long-anchors-per-continuation", 0,
    ),
    "shared-value": _args(
        "--max-context", 16384,
        "--kv-capacity", 16384,
        "--max-concurrency", 1,
        "--device-state-slots", 3,
        "--host-state-slots", 0,
        "--host-kv-mib", 0,
        "--max-private-continuations", 1,
        "--max-shared-prefixes", 1,
        "--max-long-anchors-per-continuation", 0,
    ),
    "session-order": _args(
        "--max-context", 8192,
        "--kv-capacity", 16384,
        "--max-concurrency", 2,
        "--device-state-slots", 8,
        "--host-state-slots", 0,
        "--host-kv-mib", 0,
        "--max-private-continuations", 4,
        "--max-shared-prefixes", 0,
        "--max-long-anchors-per-continuation", 0,
    ),
    "scheduler-overlap": _args(
        "--max-context", 8192,
        "--kv-capacity", 16384,
        "--max-concurrency", 2,
        "--prefill-chunk", 1024,
        "--no-prefix-reuse",
    ),
    "scheduler-prefill-128": _args(
        "--max-context", 8192,
        "--kv-capacity", 16384,
        "--max-concurrency", 2,
        "--prefill-chunk", 128,
        "--no-prefix-reuse",
    ),
    "scheduler-prefill-4096": _args(
        "--max-context", 8192,
        "--kv-capacity", 16384,
        "--max-concurrency", 2,
        "--prefill-chunk", 4096,
        "--no-prefix-reuse",
    ),
    "scheduler-backfill": _args(
        "--max-context", 7744,
        "--kv-capacity", 7808,
        "--max-concurrency", 2,
        "--pending-timeout-ms", 120000,
        "--no-prefix-reuse",
    ),
    "lane-limit-8": _args(
        "--max-context", 4224,
        "--kv-capacity", 33792,
        "--max-concurrency", 8,
        "--max-pending-requests", 1,
        "--pending-timeout-ms", 120000,
        "--no-prefix-reuse",
    ),
    "pending-timeout": _args(
        "--max-context", 4224,
        "--kv-capacity", 4224,
        "--max-concurrency", 1,
        "--max-pending-requests", 1,
        "--pending-timeout-ms", 100,
        "--no-prefix-reuse",
    ),
    "context-boundary": _args(
        "--max-context", 8192,
        "--kv-capacity", 8192,
        "--max-concurrency", 1,
        "--no-prefix-reuse",
    ),
    "vision-cache": _args(
        "--max-context", 32768,
        "--kv-capacity", 32768,
        "--max-concurrency", 1,
        "--device-state-slots", 2,
        "--host-state-slots", 0,
        "--host-kv-mib", 0,
        "--max-private-continuations", 2,
        "--max-shared-prefixes", 0,
        "--max-long-anchors-per-continuation", 0,
        "--vision",
        "--media-cache-mib", 512,
        "--media-live-mib", 512,
    ),
    "vision-thread-1": _args(
        "--max-context", 32768,
        "--kv-capacity", 32768,
        "--max-concurrency", 1,
        "--device-state-slots", 2,
        "--host-state-slots", 0,
        "--host-kv-mib", 0,
        "--max-private-continuations", 2,
        "--max-shared-prefixes", 0,
        "--max-long-anchors-per-continuation", 0,
        "--vision",
        "--media-cache-mib", 512,
        "--media-live-mib", 512,
        "--media-preprocess-threads", 1,
    ),
    "vision-concurrent": _args(
        "--max-context", 32768,
        "--kv-capacity", 65536,
        "--max-concurrency", 2,
        "--vision",
        "--media-cache-mib", 512,
        "--media-live-mib", 1024,
        "--no-prefix-reuse",
    ),
    "media-cache-tight": _args(
        "--max-context", 8192,
        "--kv-capacity", 8192,
        "--max-concurrency", 1,
        "--vision",
        "--media-cache-mib", 16,
        "--media-live-mib", 128,
        "--no-prefix-reuse",
    ),
    "vision-boundary": _args(
        "--max-context", 65536,
        "--kv-capacity", 65536,
        "--max-concurrency", 1,
        "--vision",
        "--no-prefix-reuse",
    ),
    "mixed-four": _args(
        "--max-context", 8192,
        "--kv-capacity", 32768,
        "--max-concurrency", 4,
        "--vision",
    ),
}
